### ISSUE TITLE
mac稳定版，在M1上点启动就自动关闭了

### ISSUE THREAD

**Issue by mistdon** [acgist/snail#10]

**Comment by acgist** [comment]
你进入到软件目录`/Applications/snail.app`，然后用命令启动`./Contents/MacOS/snail`启动试试。

@mistdon

**Comment by mistdon** [comment]
> 你进入到软件目录`/Applications/snail.app`，然后用命令`./Contents/MacOS/snail`启动试试。
> 
> @mistdon

你好，感谢回复，试了下，还是失败，错误信息如下：
```bash
java:77)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
        at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:98)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
	at com.acgist.snail.logger.LoggerContext.error(LoggerContext.java:104)
Failed to launch JVM
```
设备信息：M1 MacBookPro ，系统 macOS Big Sur, 版本11.4

**Comment by acgist** [comment]
一定要先进入到目录，然后再执行命令。
应该是打包命令路径有问题，所以有这个错误。

@mistdon
