### ISSUE TITLE
springboot 使用报错

### ISSUE THREAD

**Issue by pangoo-reuse** [acgist/snail#14]
## 系统环境
mac

## 详细描述
使用mac 开发springboot 接入好，写好测试demo,直接运行程序报错，
使用demo如下：
`            TorrentInitializer.newInstance().sync();
            ProtocolContext.getInstance().register(MagnetProtocol.getInstance()).available(true);
            final var taskSession = MagnetProtocol.getInstance().buildTaskSession(url);
            final var downloader = taskSession.buildDownloader();
            downloader.run();`

大致报错如下：

`2022-04-18 22:19:52.386  INFO 13376 --- [  restartedMain] c.smart.mall.socket.server.NettyServer   : 启动 Netty Socket Server,0.0.0.0/0.0.0.0:9000
2022-04-18 22:19:52.636  WARN 13376 --- [  restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-04-18 22:19:52.764  INFO 13376 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2022-04-18 22:19:52.793  INFO 13376 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8090 (http) with context path ''
2022-04-18 22:19:52.807  INFO 13376 --- [  restartedMain] com.smart.mall.MallApplication           : Started MallApplication in 5.02 seconds (JVM running for 10.787)
2022-04-18 22:20:27.922  INFO 13376 --- [0.1-8090-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-04-18 22:20:27.922  INFO 13376 --- [0.1-8090-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-04-18 22:20:27.923  INFO 13376 --- [0.1-8090-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-04-18 22:20:27.947  INFO 13376 --- [0.1-8090-exec-2] com.smart.mall.interceptor.AppFilter     : params:{}
2022-04-18 22:20:27.966  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：FTP
2022-04-18 22:20:27.966  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：HLS
2022-04-18 22:20:27.966  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：HTTP
2022-04-18 22:20:27.973  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：磁力链接
2022-04-18 22:20:27.974  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：迅雷链接
2022-04-18 22:20:27.975  INFO 13376 --- [0.1-8090-exec-2] c.acgist.snail.context.ProtocolContext   : 注册下载协议：BitTorrent
2022-04-18 22:20:33.141  WARN 13376 --- [0.1-8090-exec-2] com.acgist.snail.context.UpnpContext     : UPNP端口映射失败：多重路由环境
2022-04-18 22:20:35.580  WARN 13376 --- [0.1-8090-exec-2] com.acgist.snail.context.GuiContext      : 未知GUI事件：REFRESH_TASK_STATUS
2022-04-18 22:20:36.665 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：223.88.58.194-15000

java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200) ~[na:na]
	at com.acgist.snail.net.TcpClient.connect(TcpClient.java:89) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerClient.connect(PeerClient.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.connect(PeerDownloader.java:77) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.handshake(PeerDownloader.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.buildPeerDownloader(PeerDownloaderGroup.java:182) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.lambda$buildPeerDownloaders$1(PeerDownloaderGroup.java:151) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:256) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:202) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217) ~[na:na]
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312) ~[na:na]
	... 1 common frames omitted

2022-04-18 22:20:39.221  WARN 13376 --- [Thread-Timer-01] com.acgist.snail.context.UpnpContext     : UPNP端口映射失败：多重路由环境
2022-04-18 22:20:41.083 ERROR 13376 --- [ead-BT-Timer-01] c.a.snail.pojo.session.TrackerSession    : 查找Peer异常，失败次数：1，声明地址：udp://tracker.moeking.me:6969/announce

com.acgist.snail.context.exception.NetException: UDP Tracker声明失败（connectionId）
	at com.acgist.snail.net.torrent.tracker.UdpTrackerSession.started(UdpTrackerSession.java:104) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.pojo.session.TrackerSession.findPeers(TrackerSession.java:100) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncher.findPeer(TrackerLauncher.java:96) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncherGroup.findPeer(TrackerLauncherGroup.java:102) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:41.620 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：218.242.122.76-15001

java.util.concurrent.TimeoutException: null
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:195) ~[na:na]
	at com.acgist.snail.net.TcpClient.connect(TcpClient.java:89) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerClient.connect(PeerClient.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.connect(PeerDownloader.java:77) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.handshake(PeerDownloader.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.buildPeerDownloader(PeerDownloaderGroup.java:182) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.lambda$buildPeerDownloaders$1(PeerDownloaderGroup.java:151) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:41.620 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：220.171.158.187-12345

java.util.concurrent.TimeoutException: null
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:195) ~[na:na]
	at com.acgist.snail.net.TcpClient.connect(TcpClient.java:89) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerClient.connect(PeerClient.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.connect(PeerDownloader.java:77) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.handshake(PeerDownloader.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.buildPeerDownloader(PeerDownloaderGroup.java:182) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.lambda$buildPeerDownloaders$1(PeerDownloaderGroup.java:151) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:45.267  WARN 13376 --- [Thread-Timer-01] com.acgist.snail.context.UpnpContext     : UPNP端口映射失败：多重路由环境
2022-04-18 22:20:46.085 ERROR 13376 --- [ead-BT-Timer-01] c.a.snail.pojo.session.TrackerSession    : 查找Peer异常，失败次数：1，声明地址：udp://tracker.coppersurfer.tk:6969/announce

com.acgist.snail.context.exception.NetException: UDP Tracker声明失败（connectionId）
	at com.acgist.snail.net.torrent.tracker.UdpTrackerSession.started(UdpTrackerSession.java:104) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.pojo.session.TrackerSession.findPeers(TrackerSession.java:100) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncher.findPeer(TrackerLauncher.java:96) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncherGroup.findPeer(TrackerLauncherGroup.java:102) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:46.666 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：113.195.210.146-15001

java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200) ~[na:na]
	at com.acgist.snail.net.TcpClient.connect(TcpClient.java:89) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerClient.connect(PeerClient.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.connect(PeerDownloader.java:77) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.handshake(PeerDownloader.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.buildPeerDownloader(PeerDownloaderGroup.java:182) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.lambda$buildPeerDownloaders$1(PeerDownloaderGroup.java:151) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:256) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:202) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217) ~[na:na]
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312) ~[na:na]
	... 1 common frames omitted

2022-04-18 22:20:46.694 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：183.29.153.6-12345

java.util.concurrent.TimeoutException: null
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:195) ~[na:na]
	at com.acgist.snail.net.TcpClient.connect(TcpClient.java:89) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerClient.connect(PeerClient.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.connect(PeerDownloader.java:77) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloader.handshake(PeerDownloader.java:47) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.buildPeerDownloader(PeerDownloaderGroup.java:182) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.peer.PeerDownloaderGroup.lambda$buildPeerDownloaders$1(PeerDownloaderGroup.java:151) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:51.089 ERROR 13376 --- [ead-BT-Timer-01] c.a.snail.pojo.session.TrackerSession    : 查找Peer异常，失败次数：1，声明地址：udp://retracker.lanta-net.ru:2710/announce

com.acgist.snail.context.exception.NetException: UDP Tracker声明失败（connectionId）
	at com.acgist.snail.net.torrent.tracker.UdpTrackerSession.started(UdpTrackerSession.java:104) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.pojo.session.TrackerSession.findPeers(TrackerSession.java:100) ~[snail-1.17.1.jar:1.17.1]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncher.findPeer(TrackerLauncher.java:96) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.acgist.snail.net.torrent.tracker.TrackerLauncherGroup.findPeer(TrackerLauncherGroup.java:102) ~[snail-1.17.1.jar:1.17.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-18 22:20:51.328  WARN 13376 --- [Thread-Timer-01] com.acgist.snail.context.UpnpContext     : UPNP端口映射失败：多重路由环境
2022-04-18 22:20:51.642 ERROR 13376 --- [il-Thread-BT-01] com.acgist.snail.net.TcpClient           : TCP客户端连接异常：61.149.223.187-51413`

**Comment by acgist** [comment]
这些tracker服务器应该失效了，所以连不上。
这里有些活跃的tracker服务器地址，你可以试试：https://github.com/ngosang/trackerslist
